### ISSUE TITLE
Try out Weave.jl workflow for creating and testing Jupyter notebooks

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#10]
See https://github.com/mpastell/Weave.jl and See http://weavejl.mpastell.com/latest/usage/ 

The basic problem with Jupyter is that the notebook files are nice to interact with, but difficult to write, maintain, and test.  I believe one solution is the `Weave.jl` package.

If so, we need to figure out a good workflow.  I posted for help at (https://discourse.julialang.org/t/recommended-workflow-for-creating-and-maintaining-jupyter-tutorials-weave/8163) so perhaps someone will respond.

We need to figure out the following:
- How to do we put latex in `.jmd` files
- How do we put in code that is run when producing the file
- What about code that is not run when producing the file
- How do we generate a `.ipynb` file as well as a `.pdf` file
- How can we do an automatic test of the file to make sure it hasn't changed

**Comment by jlperla** [comment]
@sevhou I played with this a little, and I think it will be a much better way to create notebooks in the future.

**Comment by jlperla** [comment]
I added some test files in https://github.com/ubcecon/computing_and_datascience/tree/master/weave_sandbox

To use this, you need to add the `Weave` package, go to that file in the REPL, and then
```
include("create_notebook.jl")
```
As usual, the first time you call it will be slow due to precompilation.

At this point, the notebook doesn't work directly since it has the wrong Jupyter kernel.  If you go into Jupyter and change the kernel, it seems to work.

**Comment by jlperla** [comment]
Posted https://github.com/mpastell/Weave.jl/issues/115 for Weave to see why the kernel generated might be wrong.  JuliaPro installation may be part of the problem...

**Comment by mpastell** [comment]
I answered on discourse as well, but for "How do we put in code that is run when producing the file" I recommend using [nbconvert](https://github.com/jupyter/nbconvert). It would be easy to output notebooks with output from running Weave, but the output won't match (by design) running IJulia so it's not a good idea.

**Comment by jlperla** [comment]
@mpastell Thanks so much for your comments.  I posted a quetsion on discourse about what might be possible with Weave.  I don't quite understand what the nbconvert workflow would be.  I thought that nbconvert takes Jupyter notebooks and converts them to HTML/etc.  I want to go in the other direction (take markup + code in a textfile and generaet a jupyter notebook, hopefully running some of the code where appropriate).

**Comment by mpastell** [comment]
I replied on discourse about the nbconvert workflow: https://discourse.julialang.org/t/recommended-workflow-for-creating-and-maintaining-jupyter-tutorials-weave/8163/11?u=mpastell . It's a a bit surprising that `nbconvert` also allows running code from a notebook.

**Comment by jlperla** [comment]
This workflow is effectively solved by the new Weave features.  We just need to figure out regression tests and test the notebook output as required.  See https://github.com/ubcecon/computing_and_datascience/blob/master/weave_sandbox/README.md
