### ISSUE TITLE
PackageCompiler + Plots, GR

### ISSUE THREAD

**Issue by arnavs** [ubcecon/computing_and_datascience#103]
@jlperla Here's what I used to bake in Plots + GR. Seems to work. Opening this in case you want to discuss or play around.

```
# If it's causing trouble, can remove the `up` below 
julia -e "using Pkg; pkg\"rm PackageCompiler; dev PackageCompiler; up; add Plots GR\""
julia -e "using PackageCompiler; compile_incremental(:Plots, :GR)"
```

After playing with it, we see the following benchmarks (a bit differently than Simon's example [here](https://nextjournal.com/sdanisch/static-plots?change-id=CQRybQ9RsNgda3xXeTctiC&node-id=67c3a2b3-e6c7-4863-962b-4034731a1726)).

## PkgCompiler

```
julia> @time using Plots
  0.000524 seconds (554 allocations: 29.516 KiB)

julia> @time gr(fmt = :png)
  0.041992 seconds (79.00 k allocations: 3.917 MiB)
Plots.GRBackend()

julia> @time histogram(randn(10^5))
  1.559925 seconds (4.04 M allocations: 209.606 MiB, 10.43% gc time)
```

## Standard

```
julia> @time using Plots
  3.129514 seconds (7.12 M allocations: 397.309 MiB, 5.76% gc time)

julia> @time gr(fmt = :png)
  0.165607 seconds (184.63 k allocations: 9.216 MiB)
Plots.GRBackend()

julia> @time histogram(randn(10^5))
 13.466788 seconds (50.02 M allocations: 2.443 GiB, 8.89% gc time)
```

**Comment by arnavs** [comment]
Note that, if you're playing around, it's useful to set an alias to the PackageCompiler image. For example, I used 

```
alias juliax='julia -J /Users/arnavsood/.julia/dev/PackageCompiler/sysimg/sys.dylib'
```

**Comment by jlperla** [comment]
Sounds like a great first step.

**Comment by arnavs** [comment]
OK cool. Just wanted to avoid pushing a Slack notification if possible `:-)`.

**Comment by arnavs** [comment]
Also, @jlperla, I think Google CoLab is a winner. Key points: 

1. Downloading notebooks is really fast, and works on a per-notebook basis (so we don't need to grab a whole repo, or an image containing a whole repo.) We could conceivably put an individual colab link atop each lecture.

2. Most lecture code I tried works "out of the box" (i.e., those that depend on `scipy, numpy, matplotlib`, etc.) Installing `quantecon` is easy (just use a cell magic, `!pip install -q quantecon`) and really fast also. 

We can do a more detailed test of it maybe next week.
