### ISSUE TITLE
Document how to add shortcut to Jupyter and Jupyter Lab, and change the start directory

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#18]
For both OS/X and Windows

For Windows: it is relatively easy.  If Anaconda was installed in  C:\bin, then:  Create a shortcut with
- Target = C:\bin\Anaconda3\Scripts\jupyter.exe notebook
- Or to use Jupyter Lab, Target = `C:\bin\Anaconda3\Scripts\jupyter.exe lab`
- Next, to have it start in a particular folder, change the "Start In" to = `c:\working`    or wherever you want.

I don't know about OS/X.  Linux you would generally have jupyter in the path, and run it from the command line.

**Comment by jlperla** [comment]
Add the comments to https://github.com/econtoolkit/julia/blob/master/README.md

**Comment by jlperla** [comment]
Jasmine: here is a small thing to start with.  I have noticed that people can get confused on a local jupyter installation which directly Jupyter starts in.  Also, people may be using the old "jupyter notebook" instead of "jupyter lab".  Can you do a quick test and writeup in the referenced README.md file?

For example, lets say people have installed a bunch of github repositories under `/working`... then if we can tell them how to start jupyter in that directory, it will help them traverse to the files instead of having to `import` them.

**Comment by jasmineyang** [comment]
Professor Perla, I think one way to do this is: 

- First, launch the OS X Terminal by typing `terminal`. 
- Then, to have it start in a particular folder, use the `cd` command: cd `~/Desktop/folder_name` if this new folder is on desktop, for example 
- Type `jupyter notebook` to launch the notebook

 Another way might be using the following commands: 
`DIR=$(dirname $0)<br/>`
`cd /Users/{username}/{folder_name}/<br/>`
`$DIR/jupyter-notebook`

Also, some commands in the introductory files seem to work only for Windows. I will try those again and edit the files, if that happens to be the case.

**Comment by jasmineyang** [comment]
Professor Perla, I updated the README.md file. I found a quicker way to change the startup directory. Usually on OS X, we have to launch Jupyter from the directory that we want to work in. However if we don't want to enter command `cd/folder_name` each time, we could set up a bash alias command. I also put a link to the corresponding tutorials in the referenced README.md file

**Comment by jlperla** [comment]
Perfect, sounds exactly the sort of thing I was thinking about. We can add
something similar on windows as well.

**Comment by jlperla** [comment]
This task looks done to me.  Close it if you think you have completed what you wanted to do?

**Comment by jasmineyang** [comment]
Yes sure, I can move on to the next task.
