### ISSUE TITLE
Modify the Dolo examples to work on both Juliabox and local machines

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#19]
Dolo.jl is now up and running on Juliabox.  In order to get it working for the students without modification, we will need to make a few changes.

We need to modify the Jupyter notebooks so they run without problems on juliabox.  A few of the key changes:
- You will see that I got rid of all of the `Pkg.add` etc. stuff.  Remember that you can't do those things on juliabox directly.
- I really like `PlotlyJS`, but it isn't all that great for submitting homeworks and is inconsistent with what we told people to use.  Can you convert the plotting over to use `Plots.jl` with the `gr()` backend?
- The `.yaml` files need to be loaded from the local directory to work on juliabox (as well as on your local machine).  There should be no hardcoding of paths.  When you test it on your local jupyter installation, you can tell people how to change the working directory so that it loads it without the full path.
- Make sure to test both on juliabox and on your local machine.

You will see that I made some of these changes in ECON546 github for the perfect foresight, but not the other one.  This will take some testing

**Comment by sevhou** [comment]
I'm converting the PlotlyJS to Plots on my local machine.

Tried the package Dolo on Juliabox, I don't know whether it's because of the server is in trouble just now or its the package, Jupyter notebooks on that is messed up when I open it. Will try later.

**Comment by jlperla** [comment]
@sevhou So, so sorry, but stop converting the graphs from PlotlyJS.

A long story,  but we may have a solution for the dissapearing plots problem wiht `PlotlyJS`

**Comment by jlperla** [comment]
To be clear, don't erase what you have done just yet, but no need to finish the task.

**Comment by sevhou** [comment]
Ok, so I'll just keep the original ones as baseline?

**Comment by jlperla** [comment]
Yeah, keep them around.  I will discuss and send out another issue today.
Been working with Spencer on PlotlyJS wihtout the warts.

**Comment by jlperla** [comment]
Actually, feel free to keep both versions in git if you have them working (or only have have the Plots.jl ones working).  Can't hurt.

**Comment by sevhou** [comment]
Gotcha

**Comment by jlperla** [comment]
Are you having success with the Dolo tutorials on juliabox otherwise?

**Comment by sevhou** [comment]
Do you mean running Dolo tutorials with Juliabox?

I deleted the Dolo package installed before by using "Reset" yesterday and after that I can't add package anymore.

Just tried a moment ago, still can't install package. But in v0.6 Juliabox says I have Dolo.jl installed, tried to run, fail to use Dolo.

**Comment by jlperla** [comment]
You don't need to install the package, it is installed by default now.
Just reset your packages entirely and start trying the code (starting with
`using Dolo`, ...) etc.

**Comment by sevhou** [comment]
Yeah I didn’t reinstalled, I just reset because I installed it before. And then I tried using Dolo, error says Unable to load, ask me to rerun Pkg.build(package), which I can’t do.

Tried restart juliabox, still won’t work.
On Feb 5, 2018, at 11:22 AM, Jesse Perla <notifications@github.com<mailto:notifications@github.com>> wrote:

You don't need to install the package, it is installed by default now.
Just reset your packages entirely and start trying the code (starting with
`using Dolo`, ...) etc.

**Comment by sevhou** [comment]
Let me try to reset it and then try again. Will let you know if it works or still fails.
On Feb 5, 2018, at 11:25 AM, Hou, Chenyu <ch38984@mail.ubc.ca<mailto:ch38984@mail.ubc.ca>> wrote:

Yeah I didn’t reinstalled, I just reset because I installed it before. And then I tried using Dolo, error says Unable to load, ask me to rerun Pkg.build(package), which I can’t do.

Tried restart juliabox, still won’t work.
On Feb 5, 2018, at 11:22 AM, Jesse Perla <notifications@github.com<mailto:notifications@github.com>> wrote:

You don't need to install the package, it is installed by default now.
Just reset your packages entirely and start trying the code (starting with
`using Dolo`, ...) etc.

**Comment by jlperla** [comment]
Just to be clear, all you are doing is:
- You it `Reset` in juliabox and let the package builder run.  No problem.s
- You pull up a new notebook and type in `using Dolo` and it gives an error?

If so, I can't reproduce....

**Comment by sevhou** [comment]
Yeah, that’s the case.

I hit the Reset again now and I’m waiting for the Package builder to finish. After that I’ll try again. Hopefully it will work.
On Feb 5, 2018, at 11:28 AM, Jesse Perla <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to be clear, all you are doing is:

  *   You it Reset in juliabox and let the package builder run. No problem.s
  *   You pull up a new notebook and type in using Dolo and it gives an error?

If so, I can't reproduce....

**Comment by sevhou** [comment]
My Package Builder stuck for some reason.

Changed to another account on Juliabox, with the default setting, can use Dolo and run the RBC code with Pyplot smoothly. I think Juliabox is working with Dolo, just for some reason my old Juliabox package manager is screwed up….

In short, it’s working
On Feb 5, 2018, at 11:30 AM, Chenyu Hou <ch38984@mail.ubc.ca<mailto:ch38984@mail.ubc.ca>> wrote:

Yeah, that’s the case.

I hit the Reset again now and I’m waiting for the Package builder to finish. After that I’ll try again. Hopefully it will work.
On Feb 5, 2018, at 11:28 AM, Jesse Perla <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to be clear, all you are doing is:

  *   You it Reset in juliabox and let the package builder run. No problem.s
  *   You pull up a new notebook and type in using Dolo and it gives an error?

If so, I can't reproduce....

**Comment by jlperla** [comment]
Great to hear.  Email juliabox@juliacomputing.com and tell them to reset
your account.  They will do it quickly.

**Comment by sevhou** [comment]
Ok! Thanks

**Comment by jlperla** [comment]
It looks like the `Plots.jl` with the `gr()` backend is going to be the best support solution for the mediumterm, so I would like to move forward on converting those `Dolo.jl` tutorials to use it (as we discussed).  I am planning to give the Dolo.jl assignment due a little after the break, so I would like to get it done before too long.

**Comment by sevhou** [comment]
Sure, will come back to you before Monday, is that ok?
________________________________________
发件人: Jesse Perla [notifications@github.com]
发送时间: 2018年2月9日 9:28
收件人: ubcecon/computing_and_datascience
抄送: Hou, Chenyu; Mention
主题: Re: [ubcecon/computing_and_datascience] Modify the Dolo examples to work on both Juliabox and local machines (#19)

It looks like the Plots.jl with the gr() backend is going to be the best support solution for the mediumterm, so I would like to move forward on converting those Dolo.jl tutorials to use it (as we discussed). I am planning to give the Dolo.jl assignment due a little after the break, so I would like to get it done before too long.

―

**Comment by jlperla** [comment]
Stephen: you are added on this issue, and I will give you access to the ECON546 folder to modify.

**Comment by stevenzhangdx** [comment]
Based on updates from issue 22, I thought PlotlyJS.jl is working in JuliaBox now. Do we still need to convert tutorials to using Plots.gr?

**Comment by jlperla** [comment]
If it is possible.  PlotlyJS still has issues (e.g. doesn't work on jupyter lab, juno, etc.) especially well.

**Comment by stevenzhangdx** [comment]
I thought the issue was already solved. I will keep converting it and try to get it back to you today.

**Comment by jlperla** [comment]
It is in progress, but Juno has issues with multiple plots.

The other thing is I don't want people to have to learn multiple plotting libraryes.  Plots+GR may not be perfect, but consistency is useful for people at the beginning.

**Comment by stevenzhangdx** [comment]
Both Dolo tutorials are using Plots now. Please take a look at revised Jupyter notebooks I pushed to the server of ECON546_2018.
However, the last graph in rbc_model_dolo_tutorial_revised.ipynb cannot be displayed on my Mac, but both methods I provide work well on Juliabox and my desktop (PC). The problem seems like the size of this graph is too big, which requires either increasing "NotebookApp.iopub_data_rate_limit" or reducing the size of data. I will keep finding an easier solution to it.

**Comment by jlperla** [comment]
Thanks.  Can you just overwrite the files in github (instead of calling
them "revised") and also get rid of any commented lines that use PyPlot or
PlotlyJS?  I want them as clean as possible, and people don't need the old
versions.

As for the issue you are seeing on your mac, can you try to find a way to
deal with this?  One thing to try is to load plots right above that diagram
with
using Plots gr(format="png")

If this doesn't work, then it is worth asking on julia's slack channels for
help.  https://slackinvite.julialang.org/ is how you get an invite, and you
can chat realtime with the developers.

**Comment by stevenzhangdx** [comment]
I uploaded the cleaned files and removed two "revised" ones. 

Setting "gr(format="png") is not working to my device. It throws out errors that no image can be found. There is a feasible solution to this problem, see https://github.com/jupyter/notebook/issues/2287. For my case, I increase the data rate limit from the default to "iopub_data_rate_limit=10000000000" in file "NotebookApp.py" and restart Jupyter Notebook to update the change, then the image is successfully loaded. It seems that this occurs when you are trying to visualize heavy projects.

**Comment by jlperla** [comment]
Hmm, seems like a tough workaround for non-technical users to deal with.  Can you try lowering the amount of simulations to see if you can get below the threshold?  If not, then put in a comment in the file right above the graph to tell people what to do?

After that, I think it is safe to close the issue.

**Comment by jlperla** [comment]
@stevenzhangdx Sorry I got it wrong on the png.  try
` gr(fmt=:png)` right above the offending graph and see if it works.

**Comment by stevenzhangdx** [comment]
It still returns "no image found" when I am using "gr(fmt=:png)".
I reduced the number of simulation to 40 (it seems to be the largest accepted number of simuations). Now graphs can be visualized without changing data rate limit and most features are reserved. Please take a look at it.

**Comment by jlperla** [comment]
These look good to me.  I changed the files to clean up a few magic numbers.  Steven, if you have a chance to post up any issues you have on the `gr(fmt=:png)` issue as a bug in https://github.com/JuliaPlots/Plots.jl/issues it might be useful to them.  I don't have any issues, and it is supposed to fix that issue you are seeing with the iopub_data_rate_limit
