### ISSUE TITLE
Test PlotlyJS in juliabox and a local installation of Jupyter/JupyterLab, Juno and the REPL

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#22]
We are trying to decide if the `PlotlyJS.jl` is a viable alternative to plotting with `Plots.jl` and the `GR` backend.   At this point, we think that (with a small tweak) to the setup, it may be the magical short-term solution to plotting insanity in julia.  

@sglyon is the author of the package, and could use our help verifying the setup on different machines and submitting bugs as required.  Submit the bugs to https://github.com/sglyon/PlotlyJS.jl/issues

@jasmineyang  I was hoping you could test things out a bit to see if you find any bugs, or find the environment stable.  The things to look for are plots that disappear when you close and reopen notebooks, etc. as well as setup problems.

The big change we make from the previous descriptions is that we will call the `init_notebook(true)` function.  For example the following could be in a single Jupyter cell (which you want to keep separate from the plotting ones!)
```julia
using PlotlyJS
init_notebook(true)
```
Then in the next cell, you could just do
```julia
p = plot(rand(4))
display(p)
```

A few things to test:
1. Try saving that as a Jupyter notebook, and then reopening it to see if the plot disappears.
2.  Just generally try to work in the notebook, etc. to see if things ever go missing
3. Make sure that "Print Preview" works for displaying the graphs
4. Open/close/open/etc.  Just trying to find 

I also want to test:
- Juliabox.com
- Local jupyter notebook
- Local jupyter lab
- Local Juno
- Local from the REPL

The idea is that we can find whatever bugs are needed to fix so the same sort code works in all scenarios.

One note.  If you have installed on a local machine, will may to call: `Blink.AtomShell.install()` in the REPL or in a jupyter session.  Hopefully only once (or at least until things are upgraded).

**Comment by jlperla** [comment]
I am going to push this off to concentrate on other tasks.  I think that `Plots.jl` + `gr()` backend is the way to go for now.

**Comment by jasmineyang** [comment]
Professor Perla, `PlotlyJS.jl` works fine in JuliaBox and in all other local environment except **jupyter lab**. I tried a few times from my local jupiter lab and no plot shows up after running the command. Another thing is that a warning message saying "IOPub data rate exceeded" will appear in all environments when I call the `init_notebook(true) function` for the first time. This message will disappear if I re-run the command. But that seems not to be an issue.

**Comment by jlperla** [comment]
Perfect, thanks. The main task to move onto is https://github.com/ubcecon/computing_and_datascience/issues/24

**Comment by sglyon** [comment]
FYI: to use plotly in jupyterlab you need https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension

I thought it came built-in but I guess not.

It could be something that I install "if possible" with PlotlyJS.jl, but we'll have to remember that for later down the road when the dust from the recent jupyterlab release dust settles

**Comment by jlperla** [comment]
Thanks Spencer. It also could be that we were testing on older
jupyterlab(or prior to a package update on Julia) . Looking forward to
trying it out more when the dust settles, as jupyterlab sure is slick.

I am happy that PlotlyJS.jl seems to have passed the smoke test.

Also: Jasmine will be setting up some of the fixed point examples and tests
for NLsolve
