### ISSUE TITLE
Setup development environment for NLsolve library and get ready to test fixedpoints

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#24]
We want to get an interface tested for fixed point operations inside of the NLSolve library.  See https://github.com/JuliaNLSolvers/NLsolve.jl/issues/144 for a discussion.

To get ready for this, do the following:
- [x] Get yourself setup on julia slack: https://slackinvite.julialang.org/ and ping me and @pkofod 
- [x] Install the https://github.com/JuliaNLSolvers/NLsolve.jl library on your local computer
- [x] Make sure you can run the tests. i.e. https://github.com/JuliaNLSolvers/NLsolve.jl/blob/master/test/runtests.jl would be installed.
- [x] Watch the parts of https://www.youtube.com/watch?v=tx8DRc7_c9I which tell you about how to edit the code in a package (you can skip the parts about setting up a new package and setting up CI since it would already be done).  Hopefully this can give you a sense of how pull requests, etc. work.
- [x] Also take a look at https://docs.julialang.org/en/release-0.6/manual/packages/#Making-changes-to-an-existing-package-1

Patrick (@pkofod) might be able to point you in the right direction for how you will go about adding and editing tests.

After you are setup, we will talk about what the code we would want to add as tests and examples.

**Comment by jasmineyang** [comment]
Profesor Perla, I'm ready for next steps.

**Comment by jlperla** [comment]
Spectacular! I know how much work this was, but it is a good investment in learning about open source projects. I will post up some next steps soon
