### ISSUE TITLE
Get function call from Interpolations.jl working and submitted as a PR

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#26]
See https://github.com/JuliaMath/Interpolations.jl/issues/198#issuecomment-370524650 for a starting point.  I want to add support (not replace) for calling the Interpolations.jl library with () rather than [].

- [x] First, you will need to identify the different ways that the interpolations can be called with the `[]` notation.
- [x] The amount of code for this actual change will be relative simple, but it will take you some time to figure it out.  See https://github.com/JuliaMath/Interpolations.jl/issues/198#issuecomment-370524650 for hints.  Basically, you just need to forward the `[]` calls to `()` for the key types.
- [x] Then you need to adjust or add the appropriate tests in https://github.com/JuliaMath/Interpolations.jl/tree/master/test
- [x] Then you need to adjust the appropriate documentation in https://github.com/JuliaMath/Interpolations.jl/tree/master/doc
not just the (small) change you need to add, but also add in the necessary tests and simple documentation changes.  

We should have this as a full-fledged PR so that someone can just look at this, approve, etc.  You can discuss any details on here that are unclear.

**Comment by chiyahn** [comment]
I have completed implementing method calls with corresponding new unit tests passed. 

One drawback of my approach was that I had to define this for all derived types being used for interpolation, including `GriddedInterpolation` and `BSplineInterpolation`, which makes the code a bit ugly. An intuitive way to deal with this would be to define it in `AbstractInterpolation` that all these types are derived from instead, but it seems like defining a _concrete_  method in an abstract type is not supported in the most recent version of Julia. There have been some relevant discussion in https://github.com/JuliaLang/julia/issues/14919. 

There are other work arounds, like using macros or redefining `AbstractInterpolation` as a concrete type, which all I have tried, but they all suffer from either code instability or need of significant changes in the code. At this moment it seems like manually defining function calls for all concrete subtypes would be the most reasonable choice, but I am afraid this would not be an efficient way to handle it, as all subsequent contributors who want to add new concrete types of interpolation (if there are) have to implement a function call feature manually.

**Comment by jlperla** [comment]
Sounds great.  Yes, sounds like Chris said you would need to implement it for all derived types.  A pain, but so be it.  Did you add document changes as well in the checklist?  If we want to try to get them to take this as a PR, we would need that to be complete.  After that, why don't you create a PR and submit it to the library.  I will then ask a few people to review it.

**Comment by chiyahn** [comment]
No problem! Pull request has been made here: https://github.com/JuliaMath/Interpolations.jl/pull/206

**Comment by jlperla** [comment]
Spectacular!

Are you able to request code reviews on your PR?

**Comment by chiyahn** [comment]
I believe I have to wait until the repo owners assign a reviewer; is there a way of asking someone to do so? 😮

**Comment by jlperla** [comment]
I am going to try to see if I can get people to look at it sooner rather than later.  Do you want to take a break in the meantime, or are you ready for more issues!

**Comment by chiyahn** [comment]
I am definitely ready for more issues 😎

**Comment by jlperla** [comment]
OK, I think this is almost ready to be closed out.  After the arguments on your PR about the best strategy, there was agreement on comment https://github.com/JuliaMath/Interpolations.jl/pull/206#issuecomment-402281931

Basically, on your PR:
- [ ] Change the https://github.com/JuliaMath/Interpolations.jl/blob/master/README.md to only use the `()` notation
- [ ] Make sure that all of the `[]` to `()` changes in the README.md actually work!
- [ ] Put a comment at the top of that saying `[]` will be deprecated in the future

After that, tell me and I will ask Spencer to merge it.

**Comment by chiyahn** [comment]
Task complete! Note that I have created separate unit tests for examples included in README.md in `test/readme-examples.jl` with a change in `test/runtests.jl` accordingly.

Should I notify maintainers of the change in PR?

**Comment by jlperla** [comment]
I think the last thing that the maintainer seemed to want was an Issue added which gives a sense roughly of what would be needed for a full deprecation of `[]`.  After you create that issue. I would ping `sglyon` on that PR (pointing to the issue) and say that you think you have done everything they have asked in that, that you would like them to do a final check and merge?

**Comment by chiyahn** [comment]
No problem! I made a new issue here: https://github.com/JuliaMath/Interpolations.jl/issues/212

**Comment by jlperla** [comment]
OK, let me ping them then.  I think we can close this issue!
