### ISSUE TITLE
Try out  Literate.jl workflow for jupyter notebooks and document it

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#27]
The https://github.com/fredrikekre/Literate.jl is supposed to allow generation of jupyter notebooks.  It would be great if we could write all of our Jupyter tests/tutorials with this.

Documents should go in the tutorials repository.

**Comment by jlperla** [comment]
Lower priority, but worth playing with. Feel free to use this repository as a scratch pad

**Comment by ArnavSood** [comment]
@jlperla I gave this a shot. It's really neat. This is how you call the code. Workflow doesn't require much except a `generate_docs` file, that has some code like the following. Plotting on Jupyter notebooks works flawlessly. 

```
using Literate

import Plots

function update_date(content)
    content = replace(content, "DATETIME" => Date(now()))
    return content
end

Literate.markdown(pwd() * "\\julia_sandbox\\literate_test.jl", pwd() * "\\julia_sandbox\\"; preprocess = update_date)
Literate.notebook(pwd() * "\\julia_sandbox\\literate_test.jl", pwd() * "\\julia_sandbox\\"; preprocess = update_date)
Literate.notebook(pwd() * "\\julia_sandbox\\literate_test_2.jl", pwd() * "\\julia_sandbox\\"; preprocess = update_date)
```

Let me know if you'd like me to write a tutorial on this or something.

**Comment by ArnavSood** [comment]
Results are in 0451b5f.
