### ISSUE TITLE
Figure out `compat.jl`

### ISSUE THREAD

**Issue by ArnavSood** [ubcecon/computing_and_datascience#35]
Apparently this is good for moving between 0.6 and 0.7

**Comment by jlperla** [comment]
This one I know how to answer:  Compat is intended to be a way for package maintainers to have support for several versions at Julia at once.  For our stuff, we are likely going to stick with v0.6 until we can make a full switch over at once, so it is not that crucial for our main uses (though you may need to work with it when you do your open source contributions to packages).  Down the road, the easiest way to convert over to v0.7 will be through https://github.com/JuliaComputing/FemtoCleaner.jl  but we don't need to worry about that yet.
