### ISSUE TITLE
Keyword constructor for named tuples in the Parameters.jl package

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#45]
https://github.com/mauro3/Parameters.jl/issues/55#issuecomment-397158562

This can be v0.7 specific.

**Comment by jlperla** [comment]
Mauro is willing to guide you if you start looking at stuff.  You could start with a PR which you keep working on an get his advice as you go through.  The key things to get working are:
- [ ] Ensure matches his comments for the interface
- [ ] Add all sorts of tests
  - One key one is the `f=f` test where `f(x) = x` was defined above it... In and out of funcionts
  - Others include clashing names, etc. to test macro and scoping hygeine
- [ ] Add documentation/examples
- [ ] Get it working on v0.7 with the built in named tuples.

**Comment by ArnavSood** [comment]
Read through the Discourse post. Cool, this sounds like a good PR. Will do.

**Comment by jlperla** [comment]
See my comments on the issue.  Try to go back to the original and tweak it rather than completely changing the approach.  At this point, the only issue we know is that `f=f` doesn't work for functions in certain circumstances.  The best thing to do is start by writing the test for every case with the original code, make sure you can replicate the `f=f` issue in the test, and then isolate why it might be failing.

**Comment by ArnavSood** [comment]
Alright, sounds like a reasonable approach. Although I think the reason it fails for functions is the same reason it fails, for (say) an array or an int (like the earlier [discourse issue](https://discourse.julialang.org/t/macro-challenge-factory-for-creating-named-tuples/9748/20) you posted, which you can replicate with arrays). 

Maybe there's something weird happening with scoping. Or maybe there's an issue with creating an object of type `NamedTuples._NT_a_b_w(a, b, w)` in this situation (not sure, just spitballing). But I'll check it out.

**Comment by ArnavSood** [comment]
Think we're good on this, so closing. We can reopen if we want to add any new functionality or discover any issues @jlperla @mauro3
