### ISSUE TITLE
MATLAB and VSCode

### ISSUE THREAD

**Issue by ArnavSood** [ubcecon/computing_and_datascience#52]
@jlperla Let me know if you think this is worthwhile. There's a `MATLAB` package, and you can give it the path to the `mlint` linter. From there, we can figure out the best way to run code from the package (say, install `Code Runner` (which is good to do anyways) and configure it with the right command line arguments).

**Comment by ArnavSood** [comment]
Ordinarily, it makes sense to use MATLAB's IDE for m-files. But I don't like having one IDE for MATLAB, and one for everything else. And there are features of VSCode (snippets? gitlens? refactoring support?) which we might enjoy while using MATLAB.

**Comment by jlperla** [comment]
Nah. We aren't teaching with the matlab, and

**Comment by ArnavSood** [comment]
OK no problem.
