### ISSUE TITLE
Language versions in VSCode?

### ISSUE THREAD

**Issue by ArnavSood** [ubcecon/computing_and_datascience#54]
Could be good to document this workflow. AKA, how to support Julia 0.6.2 and Julia 0.7, or Python 2.7 and Python3.

**Comment by ArnavSood** [comment]
(I guess this doesn't matter so much for students taking courses, but it could for RAs or grad students working on packages).

**Comment by jlperla** [comment]
I think we basically want to wait until 0.7 is sufficiently stable, and then update to support it... Or let the vscode guy do it. Python should always be 3.6

**Comment by ArnavSood** [comment]
OK. What do you recommend for this workflow in the time being? My current strategy is to write the package locally and use Travis to test it, which isn't great.

**Comment by jlperla** [comment]
I don't understand. Stay on v0.6 for now? Wait until v0.7 is ready and
other people have documented it

**Comment by ArnavSood** [comment]
The use case here was submitting a PR to a repo that's already been moved to v0.7.
