### ISSUE TITLE
Add test of QuantEcon McCall code to the fixed-point testsuite to compare performance.

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#57]
Look at https://lectures.quantecon.org/jl/mccall_model_with_separation.html
I think the key code is
```julia
using Distributions

# A default utility function

function u(c::Real, σ::Real)
    if c > 0
        return (c^(1 - σ) - 1) / (1 - σ)
    else
        return -10e6
    end
end

# default wage vector with probabilities

const n = 60                                   # n possible outcomes for wage
const default_w_vec = linspace(10, 20, n)      # wages between 10 and 20
const a, b = 600, 400                          # shape parameters
const dist = BetaBinomial(n-1, a, b)
const default_p_vec = pdf.(dist, support(dist))

mutable struct McCallModel{TF <: AbstractFloat,
                           TAV <: AbstractVector{TF},
                           TAV2 <: AbstractVector{TF}}
    α::TF         # Job separation rate
    β::TF         # Discount rate
    γ::TF         # Job offer rate
    c::TF         # Unemployment compensation
    σ::TF         # Utility parameter
    w_vec::TAV    # Possible wage values
    p_vec::TAV2   # Probabilities over w_vec

    McCallModel(α::TF=0.2,
                β::TF=0.98,
                γ::TF=0.7,
                c::TF=6.0,
                σ::TF=2.0,
                w_vec::TAV=default_w_vec,
                p_vec::TAV2=default_p_vec) where {TF, TAV, TAV2} =
        new{TF, TAV, TAV2}(α, β, γ, c, σ, w_vec, p_vec)
end

"""
A function to update the Bellman equations.  Note that V_new is modified in
place (i.e, modified by this function).  The new value of U is returned.

"""
function update_bellman!(mcm::McCallModel,
                         V::AbstractVector,
                         V_new::AbstractVector,
                         U::Real)
    # Simplify notation
    α, β, σ, c, γ = mcm.α, mcm.β, mcm.σ, mcm.c, mcm.γ

    for (w_idx, w) in enumerate(mcm.w_vec)
        # w_idx indexes the vector of possible wages
        V_new[w_idx] = u(w, σ) + β * ((1 - α) * V[w_idx] + α * U)
    end

    U_new = u(c, σ) + β * (1 - γ) * U +
                    β * γ * dot(max.(U, V), mcm.p_vec)

    return U_new
end


function solve_mccall_model(mcm::McCallModel;
                            tol::AbstractFloat=1e-5,
                            max_iter::Integer=2000)

    V = ones(length(mcm.w_vec))    # Initial guess of V
    V_new = similar(V)             # To store updates to V
    U = 1.0                        # Initial guess of U
    i = 0
    error = tol + 1

    while error > tol && i < max_iter
        U_new = update_bellman!(mcm, V, V_new, U)
        error_1 = maximum(abs, V_new - V)
        error_2 = abs(U_new - U)
        error = max(error_1, error_2)
        V[:] = V_new
        U = U_new
        i += 1
    end

    return V, U
end
mcm = McCallModel()
V, U = solve_mccall_model(mcm)
```
With this
- [x] Get it working (essentially as-is) and add this to the `NLsolve`  ranch as a new test called `mccall.jl` or something like that.  
- [x] Maybe put it in a separate function so that you can run the `@btime` on it.  You will want to keep that version in the test as a comparison 
- [x] Now, we want to make a separate version of this using the `fixedpoint` library, and changing as little else as possible.
- [x] I think the key here is first to rewrite the `update_bellman!` to be an inplace function which can be used with a fixed point iteration.
   - rename the `update_bellman!` function to be `bellman_operator!` or something like that
   - move the `mcmc::McCallModel` to the end of the signature
  - In particular, this means you will want to change the signature to `not` return `U_new` but rather to have the whole thing in a single vector with the `V_new` and `U_new` stacked and the `V` and `U` stacked.  Then it becomes a true fixed point operator on a vector
 - Get that working fully first, where the `solve_mccall_model` function is modified to use the changed `bellman_operator!` function, but leave the rest of fixed point iteration the same.
  - Check the performance of this with a `@btime` compared to the original code, to make sure that this didn't add a huge amount of overhead.
- [x] After that, you can modify the iteration in `solve_mccall_model` to use the `bellman_operator!` with the `fixedpoint` function you designed.  This probably involves creating a simple closure in that function prior to calling it.  i.e. 
```julia
T!(x_new, x) = bellman_operator!(x_new, x, mcm)
#...
solution = fixedpoint(T!, x0, inplace=true, ftol=tol)
```
- [x] Make sure that you are using the same tolerances, and do a `@btime` to see if there is a difference.  Try it with `m=1` or `m=2` as well.

**Comment by ArnavSood** [comment]
Makes sense. I'll probably step out for lunch and then get to this.

**Comment by ArnavSood** [comment]
Done. See commit XYZ for benchmarking code and 

What we see is that two simple iteration schemes are about as fast as each other (~513 μs naive, and about 580 μs stacked), and all the `nlsolve()` schemes are about 2X slower (for various memory parameters `m`). 

Code is up at 50077b5 for inspection. It's possible (maybe even probable) there's some type instability somewhere, so I'll look into that.

**Comment by ArnavSood** [comment]
50077b5

**Comment by ArnavSood** [comment]
@jlperla OK, I'm going to close this since the code is up at the server since the tests pass and obey the speed rules we think they do. 

But it's worth looking at the accuracy here; all the results converge by `nlsolve()`'s `ftol <= 1e-5` rule. But the roots found by different `m` values are pretty far apart (`1e-4, 3e-4, 1e-6` for pairwise consecutive on 0, 1, 2, 7). It's probably still true that these all end up close enough to where the Bellman operator sends them. But this is probably the kind of thing users would need to know. 

What's interesting is that roots found by the higher `m` values (which run faster) are closer together.

**Comment by ArnavSood** [comment]
Just confirming that all the solutions here are equally accurate, in that their difference from their successor under Bellman iteration is less than required. 

```
norm(old - cat(1, U_new, V_new), Inf) = 9.670017810492482e-6 # QuantEcon implementation 
norm(default_fixedpoint_results.zero - newVec, Inf) = 9.867365108107151e-6 # m = 0 
norm(fixedpoint_results_1.zero - newVec, Inf) = 7.116237924265079e-6
norm(fixedpoint_results_2.zero - newVec, Inf) = 2.3626285639011257e-7
norm(fixedpoint_results_7.zero - newVec, Inf) = 1.399587077344222e-7
```
