### ISSUE TITLE
Get minimalist Python setup done in the tutorial

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#63]
We want the simple tutorial to have the installation steps for python, with a similar complexity to the https://github.com/econtoolkit/tutorials/blob/master/julia.md#installing-julia-on-your-desktop and the https://github.com/econtoolkit/tutorials/blob/master/vscode.md#setup-for-julia section.

The goal is that someone can just follow the exact steps, and they will be able to run python code in the vscode editor (and also use jupyter).

- [x] Link to https://lectures.quantecon.org/py/getting_started.html  for sure
- [x] For the basic python installation, if all you had to do in https://lectures.quantecon.org/py/getting_started.html was to install the linked conda and choose "default Python installation", then that step may be very easy.
- [x] Lets assume people would need the `QuantEcon.py` package in that installation as well, so make sure that is in the step
- [x] If you needed to do anything else to get fancy stuff working (e.g. setup for matplotlib, using matplotlib with latex, etc.) then we can add that in the list too.
- [x] Then make a link to a new section you can add in the VS Code instructions in https://github.com/econtoolkit/tutorials/blob/master/vscode.md  maybe calling it "Setup for Python"
- [x] In that file, but in whatever is required to get Python working well in the editor, using something like https://github.com/econtoolkit/tutorials/blob/master/vscode.md#setup-for-julia as a template

**Comment by jasmineyang** [comment]
https://github.com/econtoolkit/tutorials/blob/master/python.md. 

Jesse, the python tutorial has been completed. Besides set-up instructions, python packages are introduced along with some specific examples. A butterfly curve example is given to demonstrate some interesting functions that can be plotted using matplotlib.

**Comment by jlperla** [comment]
@jasmineyang  Thanks so much, it looks spectacular!

**Comment by jlperla** [comment]
My only immediate feedback is that it would be nice if the butterfly curve example was something you could copy/paste when you were testing things out.  I put in a new placeholder for a `.pynb` document for it in the folder `/python/butterfly.ipynb`  which you could but the code in and link to?

**Comment by jasmineyang** [comment]
great, I will do that.
