### ISSUE TITLE
Jupinx with Julia v0.6

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#68]
Following #61 

Modify a copy of the simple https://github.com/QuantEcon/sphinxcontrib-jupyter.minimal repository to get the `simple_notebook.rst` page working with julia.  You can put it in somewhere in https://github.com/ubcecon/computing_and_datascience/tree/master/julia_sandbox

If I had to guess, you may need to tweak the `kernelspec` in the `conf.py` file to be consistent with the installed julia kernel, as described in https://github.com/QuantEcon/sphinxcontrib-jupyter

- [ ] Try to see the different between the default for a code-block and the `:class: no-execute`
- [ ] What happens if you generate a plot in source?  
- [ ] How do you have code that executes but is not visible?
- [ ] or extra credit, if you have Julia v0.7 working in IJulia, you could see if that works.

**Comment by ArnavSood** [comment]
Sounds good. And that sounds about right for the implementation.

**Comment by jlperla** [comment]
For plotting libraries, I think it is useful to see if the following work:
- [ ] https://github.com/fredo-dedup/VegaLite.jl also
- [ ] Plots.jl with the GR backend
- [ ] Ulitmately https://github.com/sglyon/PlotlyJS.jl
