### ISSUE TITLE
Prepare Julia introduction seminar for 1-1.5 hours

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#7]
See https://github.com/econtoolkit/julia for a description of the setup for julia

Good sources include those in https://github.com/econtoolkit/julia/blob/master/tutorials.md

I think the tutorial should do the following:
- Make sure people see how to startup next.juliabox.com (or https://pims.syzygy.ca/ when it is operational) with Julia)
- Do everything in Jupyter notebooks, which we can store in the https://github.com/econtoolkit/julia repository
- Go through the basics of julia and simple linear algebra.

Luckily, I think that the material in https://github.com/econtoolkit/julia/blob/master/tutorials.md probably has most (or all?) of what you need to do.
- First, I would save the tutorials in https://next.juliabox.com/ into our repository as a baseline.
- Then I would store some Jupyter notebooks for https://lectures.quantecon.org/jl/julia_by_example.html and https://lectures.quantecon.org/jl/julia_essentials.html
  - At this point, those are not available directly as notebooks, so we can copy/paste code as required
  - Hopefully at some point, we can see http://discourse.quantecon.org/t/are-there-any-jupyter-notebooks-for-julia-intro-lecture-slides/340 and there may be automatic-generation
- Last, it is worth going through a few useful tricks in the Jupyter environment
   - In particular, how to write out math as latex code
   - How to add in symbols and variable names based on latex symbols (e.g. `\alpha<Tab>

From those, I would play around to see what you think a reasonable amount of material to do in an hour  or hour and a half.

**Comment by jlperla** [comment]
There is a youtube of the julia crew goinng through their notebooks.  See https://discourse.julialang.org/t/december-19-julia-tutorial-streaming-over-youtube/7734/8  She says she will try to get them setup on github, so at that point we may be able to skip downloading ourselves.

**Comment by jlperla** [comment]
youtube link is: https://www.youtube.com/watch?v=4igzy3bGVkQ

**Comment by sevhou** [comment]
The Juliabox seems to work well on my labtop, I think Jupyterhub is not supporting Julia yet (only Python and R as on my computer). Several things to clearify:

1. As I already installed Julia,but the Juliabox is Julia-installation free right? Which means students dont need to install Julia first to get it to work? Because I can see two different versions of Julia through Juliabox but on my Jupyter there are three. I assume this is also why you need to click on menus of Juliabox to add package right？

2. I do think QuantEcon website and Juliabox have more than enough materials on Julia. The tutorial should cover whatever you think is necessary for them to do the HWs I guess? And I think I also need to teach them a bit about latex context because their HWs should be directly through Jupyter notebook right?

3. I'm not sure whether they can submit HW directly through Juliabox, I used my Github account to access Juliabox, do they have to have a Github account? I think they can also get access using google or other things, then how do you want them to hand in the assignments?

Regarding the materials I think we can talk about it when we meet, it depends on what you want them to do using Julia.

**Comment by jlperla** [comment]
> I think Jupyterhub is not supporting Julia yet  
Do you mean the https://pims.syzygy.ca/ ? Otherwise, there are ways to install it for JupyterHub (each language/version in Jupyter is called a "kernel") , but it is not something we want to worry about too much yet since we can hopefully get other people to manage it.  JupyterHub is basically software to run Jupyter in a multi-user setup.  

> As I already installed Julia,but the Juliabox is Julia-installation free right? Which means students dont need to install Julia first to get it to work?
Exactly.  Your jupyter installation may have different kernels setup by JuliaPro.

> I do think QuantEcon website and Juliabox have more than enough materials on Julia. The tutorial should cover whatever you think is necessary for them to do the HWs I guess
Yes, I think that those two sources have plenty of content.  The question will be what to collate for them and how long will it take.  If we focus on taking things as far as we can in 1.25 hours (at a reasonable pace) then that is perfect.  Hopefully we can get through the basics of functions, loops, variables, matrices/arrays, list comprehensions, and some basics of generic types.

We will also pass students the link to https://www.youtube.com/watch?v=4igzy3bGVkQ

> I'm not sure whether they can submit HW directly through Juliabox, I used my Github account to access Juliabox, do they have to have a Github account? I think they can also get access using google or other things, then how do you want them to hand in the assignments?
I was planning to have them forward the Jupyter notebooks (i.e. the `.ipynb` files) for each hopework, and probably save off a PDF version of it for good measure.  That said, I will tell them all to setup github accounts.

Yes, I think it is useful to show them how to input a latex formula in a Jupyter cell, though we don't need to get too fancy.

**Comment by sevhou** [comment]
That sounds great.

I think functions, loops and defining variables should be included for sure, also graph plotting and matrix computation. I think it is worth going through some examples, do you have small examples in mind? I can code it up a bit and show the example to them in the tutorial I think.

And we are talking about the master course right?

Are you around tommorow? We can talk if you want.

**Comment by sevhou** [comment]
Definitely, I'll do both and if there's time left I can try to do the excercise in https://lectures.quantecon.org/jl/julia_by_example.html this as well

**Comment by jlperla** [comment]
Based on our discussion: I reorganized the tutorials a little bit.  Put whatever Jupyter tutorials you make in https://github.com/econtoolkit/julia/tree/master/tutorials
