### ISSUE TITLE
Test out docker with datascience stack 

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#72]
I think this is a good docker stack to play with: https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook

Also http://jupyter-docker-stacks.readthedocs.io/en/latest/index.html for general notes on this stack

To test:
- [x] How to download and run it and start up Jupyter
- [x] How to start it with Jupyter but able to open and save in a local directory
- [x] How to start it and go into the Juila REPL
- [x] How does the julia REPL load and save local files.
- [x] Can the Julia REPL install new packages easily? (it is OK if the answer is no)   With v1.0 we might have it use a local filesystem as an alternateive package 

I would ask around, though, as this might not be the most minimal stack for this kind of stuff.

**Comment by jasminefish000** [comment]
Some note was taken while doing the test run:

1. Install Docker see https://docs.docker.com/install/, should expect to see an executable file.
For Mac, https://store.docker.com/editions/community/docker-ce-desktop-mac
For Windows, https://store.docker.com/editions/community/docker-ce-desktop-windows

2. Test run: to test run Docker, run `docker version`, and `docker run hello-world`. This provides you with a test-run of a docker, and give the information whether docker is installed correctly.
Test run web server `docker run -d -p 80:80 --name webserver nginx`.
To see installed docker container `docker container ls`.

3. After installing docker, run `docker run -p 8888:8888 jupyter/scipy-notebook:2c80cf3537ca`

**Comment by jasminefish000** [comment]
A introduction of how to run docker with atom
https://github.com/dformoso/docker-atom-tutorial
