### ISSUE TITLE
Investigate adding Julia 1.0 to a datascience stack 

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#73]
This is a tougher one, and one that depends on #72  as well as more stability in Julia 1.0 packages.   After #72 we can start asking around to see if anyone else is working on it, at which point we could try to port over a stack.  As before, add notes to the `README.md` and put files for in the https://github.com/ubcecon/computing_and_datascience/tree/master/docker directory.

The key features we would need to add in, outside of the normal jupyter/julia/etc., are:
- [x] How do we preinstall packages and then precompile then as part of the script.  e.g. `] add Plots DifferentialEquations; precompile` 
- [x] Is it possible for users of the stack to do their own `] add` or `] up`?  The reason it might not be is that the docker filesystem is read-only for this sort of stuff.  The solution might require looking into the new pacakge system.  In particular, modifying `JULIA_DEPOT_PATH` or something like that.  See https://docs.julialang.org/en/stable/stdlib/Pkg/#Glossary-1
- [ ] Can you use Plots.jlf rfom the REPL or Jupyter

**Comment by jlperla** [comment]
See https://hub.docker.com/r/library/julia/ which seems to have a new v1.0 docker image.  Might be worth playing around with that a little, adding a package installation and precompilation to an image using it as a base, etc.

At this point, I think we should hold off on getting the docker stuff up and running with Jupyter and the datascience stack, but we might be able to help others out there.

**Comment by jlperla** [comment]
A few other links to keep track of:
- https://github.com/jheinen/GR.jl/commit/3030ae6f99fd4650062e57b9be6a545b1f082ecb
- https://nextjournal.com/sdanisch/plots-pyplot
- http://eu.gcr.io/nextjournal-com/environment@sha256:6f79164671b0b2e73cce884a8749d65c466d317815f70be64d2fdb367ebb7ae1
- https://nextjournal.com/a/KAKVnxFSx4LUo6McDM7mB?change-id=CJ131JkfVKW7cuwRjWQwJJ&node-id=e8f2328c-62cf-4dca-849f-73746f78304c

**Comment by jasminefish000** [comment]
- How to start a Julia REPL with a docker:
`docker run -it --rm julia`, -i is for the interactive. -t allocates psuedo-tty.
`docker run -it --rm -v "$PWD":/usr/myapp -w /usr/myapp julia` 

- Once the container is started, it remains if not removed. To shut down the container, just use `exit()` inside Julia.

- To restart the container, use `docker start -i <container_id>`.

- To install a package. First `using Pkg`, then `Pkg.add("<package_name>")`.

- One thing that is confusing, when I use the package, it is precompiled.

**Comment by jlperla** [comment]
Great!


Did you try any of the docker files there for our tweaks?    In particular - [ ] Try out https://github.com/jheinen/GR.jl/commit/3030ae6f99fd4650062e57b9be6a545b1f082ecb might be a good one to base off of, since it hopefully has the `GR` plotting library working.
- [ ] From that one, it looks like we could add in installation and precompilation/etc. for key packages.  Try to add in `Parameters` and maybe `Expectations` and precompile.
- [ ] Right now that seems to install with
```
julia -e 'import Pkg; Pkg.add("GR")' && \
    julia -e 'import Pkg; Pkg.add("IJulia")' && \
    # precompile Julia packages \
    julia -e 'using GR' && \
    julia -e 'using IJulia' && \
```
but I think you can use the new package manager commands as something like:
```
julia -e 'using Pkg; pkg"add GR IJulia; precompile"' && \
``` 
The benefit of this is that we can throw a list of all of the packages and have it deal with the dependences and precompilation all at once.
- [ ] Figure out how to run the container as a jupyter server.  See https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html  for how to run jupyter.  But it would be something like
```
docker run --rm -p 10000:8888 -e JUPYTER_LAB_ENABLE=yes -v "$PWD":/home/jovyan/work ubcecon/julia-notebook
```
- [ ] Sounds like it works for the user to do their own `] add MyLibrary`  but I would do a double-check as you have above.
- [ ] I would play around with making a new docker image that is hosted on dockerhub.  I added a Docker Hub for us to play in: https://hub.docker.com/u/ubcecon/dashboard/ where you are an owner with full control.

**Comment by jasminefish000** [comment]
I encounter a problem: when I build and run using the docker image from  GR.jl/Dockerfile, I cannot open 
127.0.0.1 in the brower. 
I followed the discussion in this thread 
https://stackoverflow.com/questions/34543443/cant-access-127-0-0-1

**Comment by jasminefish000** [comment]
I tested the GR.jl.
The first thing is to compile the docker image locally. First, use `git clone https://github.com/jheinen/GR.jl.git` clone to clone the full repository locally. It is a Jupyter image with the Julia v1.0.
Then just build it locally and push it to the online docker hub.

Sometimes I have the connection refused to issue, this helped.
`docker run -it -p 8888:8888 jasminefish000/docker_test`

**Comment by jlperla** [comment]
We can't be cloning and building packages manually. Didn't the package manager work?

**Comment by jasminefish000** [comment]
Yes, the package manager works.
The image GR.jl is a docker file that I tested so that we can customize the docker image.

After starting the customized docker image with Jupyter +Julia v1.0, we can use the package manager.

**Comment by jlperla** [comment]
Oh I see. Can we talk on slack in about an hour?
