### ISSUE TITLE
Testing of vse.syzygy.ca

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#83]
The things we need to make sure work and have sufficient documentation:
- [x] Key packages, precompiled, in the existing Julia setup
- [x] Add in a user package not currently in the current precompiled setup
- [x] Add in a different version of a currently installed package in the shared repository (this could be done by changing to a different project and `] add Package#tag`
- [x] Test uploading and downloading a notebook, and document if required
- [x] Test and document cloning a github repo.
- [ ] Are there any other ways to copy files back and forth?
- [x] Document how to restart the server for users? (Ian said he was installing a way to get to the Control Panel

Lets keep this a live list, so modify as we come across stuff to check.

**Comment by jasminefish000** [comment]
There is an additional problem that, Julia works fine in the terminal. But the Julia notebook does not work for me.
It seems that the connection from IJulia to the kernel is uncertain.
I'm trying to compile the same docker image on my own laptop to see if that works locally.

In addition, I've emailed Ian about it.

**Comment by jasminefish000** [comment]
To restart the kernel,  in Jupyter lab, Help -> Launch Classic Notebook
Then use control panel -> stop my server, then control panel-> start server
