### ISSUE TITLE
Add instantiation of project.toml and manifest.toml to docker build for Syzygy

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#84]
cc: @arnavs  

@jasminefish000 : In order to maximize the chance that vse.syzygy.ca works for us, we can have it install and precompile the **exact** set of packages and versions that are required for the notebooks to work.  To make that happen, Arnav created a Project.toml and Manifest.toml files.

You can see them here: https://github.com/QuantEcon/lecture-source-jl/tree/master/notebooks

What we want to do is add these files and the activation of them to the docker image for the vse.syzygy.ca

@arnavs  can explain how to add this to a julia file, but I think it is:
```
using Pkg
pkg"activate .; instantiate; precompile"
```
Assuming that this is being run in the same folder as the toml files.  Alternatively, you may be able to give it a path.

**Comment by arnavs** [comment]
That's basically it re adding to a Julia file. Jasmine, if you want to touch base sometime tomorrow (or now, if you're still around), I work downstairs in 062.
