### ISSUE TITLE
Examples for using auto-differentiation and finite-differences with NLopt

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#89]
See http://compare-lectures.quantecon.org/jl/optimization_solver_packages.html# for the current lecture on this.  It isn't currently compiling, but you can see the text.

I would like to add in some more stuff on using NLopt.jl

The goal will be to solve the following two examples:
1. The unconstrained `max -(x_1^2 + x_2^2)` for a `x = [x_1, x_2]`
2. The constrained example in https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/ which is already implemented in https://github.com/JuliaOpt/NLopt.jl#tutorial

The difference is that I want us to pretend we don't know the gradients and jacobians, and to calculate them using AD and finite differences.

You can put temporary files in this repo as you play around with it.

For the AD, use `ForwardDiff.jl` and do your best to figure out how to easily get the solution to the function and the gradient or jacobian at the same time.

For finite differences, we will discuss more later.

**Comment by jlperla** [comment]
To be more clear here.  if you look at the NLopt docs https://github.com/JuliaOpt/NLopt.jl#tutorial
I want to be able to tell them how to change
```julia
function myfunc(x::Vector, grad::Vector)
    if length(grad) > 0
        grad[1] = 0
        grad[2] = 0.5/sqrt(x[2])
    end
    return sqrt(x[2])
end
```
into 
```julia
myfunc(x::Vector) =  sqrt(x[2])

function myfuncwrapper(x::Vector, grad::Vector)
    if length(grad) > 0
        # something to calculate the gradient using from myfunc with either AD or finite differences
        return val
    end
    return myfunc(x)
end
```
Or, eventually something even better, where we create a simple wrapper to make this seamless.

Then I want to do the same thing for constrained optimization (e.g. with the derivatives)  etc.
- [ ] The first step is to see how https://github.com/JuliaNLSolvers/NLSolversBase.jl works
- [ ] Figure out how https://github.com/JuliaNLSolvers/NLsolve.jl and https://github.com/JuliaNLSolvers/Optim.jl do it.
  * We may be able to use their convenience wrappers
  * https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/multivariate/optimize/interface.jl#L37 in particular uses the `OnceDifferentiable`, etc.
- [ ] See if we can use this inside of the myfuncwrapper function above
- [ ] See what would be needed to eliminate it entirely, so that we can generate an NLopt compatible wrapper.  i.e. 

The final result may be something like
```julia
using NLopt
using NLSolversBase

struct NLSolversBase.NLoptAdapter(f ... ) # an adapter  we could add to NLSolversBase eventually.
    # or something that adapts the arguments used by NLopt.
    # basically it just swaps the argument order/etc. for the calculations expected by NLopt
end
# This structure ends up callable, with the appropriate functions exactly what NLopt expects.


myfunc(x) = sqrt(x[2])
NLoptAdapter(OnceDifferentiable(myfunc))
function myconstraint!(x, grad, a, b) 
        grad[1] = 3a * (a*x[1] + b)^2
        grad[2] = -1
end
opt = Opt(:LD_MMA, 2)
lower_bounds!(opt, [-Inf, 0.])
xtol_rel!(opt,1e-4)

f_opt = NLoptAdapter(OnceDifferentiable(myfunc))
c_1_opt = NLoptAdapter(OnceDifferentiable((x,g) -> myconstraint(x,g,2,0)))
c_2_opt = NLoptAdapter(OnceDifferentiable((x,g) -> myconstraint(x,g,-1,1)))

min_objective!(opt, f_opt )
inequality_constraint!(opt, c_1_opt, 1e-8)
inequality_constraint!(opt, c_2_opt, 1e-8)

(minf,minx,ret) = optimize(opt, [1.234, 5.678])
numevals = opt.numevals # the number of function evaluations
println("got $minf at $minx after $numevals iterations (returned $ret)")

**Comment by chiyahn** [comment]
The first version of the notebook available at https://github.com/ubcecon/computing_and_datascience/pull/90.
